### ISSUE TITLE
Error thrown when running in Git Bash for Windows

### ISSUE THREAD

**Issue by mary-gao** [IBM-UrbanCode/ucd-stress-test#3]
When running in Git Bash for Windows, the following error will prevent build:
```
C:\Users\IBM_ADMIN\workspace\ucd-stress-test\build.xml:342: Execute failed: java.io.IOException: Cannot run program "${git}" (in directory "C:\Users\IBM_ADMIN\workspace\ucd-stress-test"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
```

**Comment by mkorejo** [comment]
Hi @mary-gao,

I finally took a look at this and seems like conditions to set the `git` property in build.xml were not being met, thus the property was not being set. I made some changes in my latest commit and tested on Windows 10:
https://github.com/IBM-UrbanCode/ucd-stress-test/commit/55a03d53e58d8d4d157b33b13bbca7a05618fb3f

I'll wait a bit to close this issue in case you are able to confirm. Thanks very much!
